
# project_id must be the first key in the config!
project_id = "pmwtujjyrfkzccpjigqm"

[global]
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"

[global.env_vars]

[[functions]]
name = "compliance-management"
verify_jwt = true
