
project_id = "seaxchrsbldrppupupbw"

[global]
SUPABASE_URL = "env(SUPABASE_URL)"
SUPABASE_SERVICE_ROLE_KEY = "env(SUPABASE_SERVICE_ROLE_KEY)"

[global.env_vars]

[[functions]]
name = "compliance-management"
verify_jwt = true

[[functions]]
name = "send-notification"
verify_jwt = true

[[functions]]
name = "document-management"
verify_jwt = true

[[functions]]
name = "create-user"
verify_jwt = true

[[functions]]
name = "process-notifications"
verify_jwt = true

