
project_id = "pmwtujjyrfkzccpjigqm"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions]
[functions.create-user]
verify_jwt = true
[functions.send-invitation]
verify_jwt = true

