
project_id = "ugjttewblqtpznfxutez"

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["https://lovable.dev"]
jwt_expiry = 3600

[functions.batch-request-email-details]
verify_jwt = false

[functions.process-batch-upload]
verify_jwt = false
