
-- Migration 14: Insert comprehensive default compliance requirements
-- Enterprise-grade compliance requirements covering all major areas and roles

-- Phase 1: Core Safety & Certification Requirements (8 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'CPR/AED Certification',
    'Current CPR and AED certification from an accredited provider',
    'certification',
    'safety',
    true,
    15,
    30,
    7,
    '{"certification_provider": "text", "certification_number": "text", "issue_date": "date", "expiry_date": "date", "additional_notes": "textarea"}',
    '{"expiry_date": {"required": true, "future_date": true}, "certification_number": {"required": true, "min_length": 5}}',
    'pdf,jpg,jpeg,png',
    5,
    false,
    'Upload your current CPR/AED certification. Must be from an accredited provider and not expired.',
    'CPR/AED certification is required for all instructional roles to ensure emergency response capability.',
    1
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Background Check Clearance',
    'Current background check clearance documentation',
    'document_review',
    'safety',
    true,
    20,
    30,
    7,
    '{"check_type": "select", "completion_date": "date", "agency_name": "text", "reference_number": "text", "notes": "textarea"}',
    '{"completion_date": {"required": true, "within_last_year": true}, "reference_number": {"required": true}}',
    'pdf,doc,docx',
    10,
    false,
    'Submit documentation of completed background check. Must be current within the last 12 months.',
    'Background checks ensure safety and trust for all personnel in instructional and supervisory roles.',
    2
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Insurance Coverage Verification',
    'Proof of current liability and professional insurance coverage',
    'document_review',
    'safety',
    true,
    25,
    30,
    14,
    '{"policy_type": "select", "policy_number": "text", "coverage_amount": "number", "effective_date": "date", "expiry_date": "date", "provider_name": "text"}',
    '{"policy_number": {"required": true}, "coverage_amount": {"required": true, "min_value": 100000}, "expiry_date": {"required": true, "future_date": true}}',
    'pdf,jpg,jpeg,png',
    5,
    false,
    'Upload current insurance certificates showing liability and professional coverage. Minimum $100,000 coverage required.',
    'Insurance coverage protects both providers and clients in case of incidents or professional liability claims.',
    3
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'OSHA Compliance Training',
    'Completion of OSHA workplace safety and compliance training',
    'training',
    'safety',
    true,
    10,
    45,
    10,
    '{"training_provider": "text", "completion_date": "date", "certificate_number": "text", "hours_completed": "number", "topics_covered": "textarea"}',
    '{"completion_date": {"required": true, "within_last_two_years": true}, "hours_completed": {"required": true, "min_value": 4}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Complete OSHA workplace safety training. Minimum 4 hours required. External training links will be provided.',
    'OSHA training ensures all personnel understand workplace safety requirements and compliance standards.',
    4
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Emergency Response Training',
    'Emergency response and evacuation procedures training',
    'training',
    'safety',
    true,
    12,
    30,
    7,
    '{"training_date": "date", "instructor_name": "text", "scenarios_covered": "textarea", "drill_participation": "checkbox", "competency_verified": "checkbox"}',
    '{"training_date": {"required": true, "within_last_year": true}, "competency_verified": {"required": true, "value": true}}',
    'pdf,doc,docx',
    3,
    false,
    'Complete emergency response training including evacuation procedures and emergency protocols.',
    'Emergency response training prepares personnel to handle various emergency situations effectively.',
    5
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Workplace Safety Assessment',
    'Annual workplace safety assessment and hazard identification',
    'assessment',
    'safety',
    false,
    15,
    365,
    30,
    '{"assessment_date": "date", "assessor_name": "text", "hazards_identified": "textarea", "corrective_actions": "textarea", "follow_up_required": "checkbox"}',
    '{"assessment_date": {"required": true}, "assessor_name": {"required": true}, "corrective_actions": {"required": true}}',
    'pdf,doc,docx,xlsx',
    10,
    false,
    'Conduct comprehensive workplace safety assessment. Document all identified hazards and corrective actions.',
    'Regular safety assessments help maintain safe working environments and prevent workplace incidents.',
    6
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Equipment Safety Inspection',
    'Regular inspection and maintenance of training and safety equipment',
    'assessment',
    'safety',
    true,
    10,
    90,
    14,
    '{"inspection_date": "date", "equipment_list": "textarea", "condition_notes": "textarea", "maintenance_needed": "textarea", "inspector_signature": "text"}',
    '{"inspection_date": {"required": true}, "equipment_list": {"required": true}, "inspector_signature": {"required": true}}',
    'pdf,xlsx,doc,docx',
    5,
    false,
    'Inspect all training and safety equipment quarterly. Document condition and maintenance requirements.',
    'Regular equipment inspections ensure safety and proper functioning of training and emergency equipment.',
    7
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Incident Reporting Training',
    'Training on proper incident reporting procedures and documentation',
    'training',
    'safety',
    true,
    8,
    30,
    7,
    '{"training_completion_date": "date", "reporting_system_access": "checkbox", "sample_report_submitted": "checkbox", "trainer_approval": "text"}',
    '{"training_completion_date": {"required": true}, "reporting_system_access": {"required": true, "value": true}, "sample_report_submitted": {"required": true, "value": true}}',
    'pdf,doc,docx',
    3,
    false,
    'Complete incident reporting training and submit a sample incident report for approval.',
    'Proper incident reporting is crucial for maintaining safety records and continuous improvement.',
    8
);

-- Phase 2: Training & Education Requirements (6 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'New Employee Orientation',
    'Comprehensive orientation program for new employees',
    'training',
    'training',
    true,
    20,
    14,
    3,
    '{"orientation_date": "date", "modules_completed": "textarea", "supervisor_signature": "text", "questions_answered": "number", "handbook_received": "checkbox"}',
    '{"orientation_date": {"required": true}, "supervisor_signature": {"required": true}, "handbook_received": {"required": true, "value": true}}',
    'pdf,doc,docx',
    5,
    false,
    'Complete all new employee orientation modules within 14 days of start date.',
    'Orientation ensures new employees understand company policies, procedures, and expectations.',
    9
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Role-Specific Training Completion',
    'Completion of training specific to assigned role and responsibilities',
    'training',
    'training',
    true,
    25,
    60,
    14,
    '{"role_training_modules": "textarea", "completion_dates": "textarea", "competency_scores": "textarea", "supervisor_approval": "text", "additional_training_needed": "textarea"}',
    '{"role_training_modules": {"required": true}, "competency_scores": {"required": true}, "supervisor_approval": {"required": true}}',
    'pdf,xlsx,doc,docx',
    10,
    true,
    'Complete all training modules specific to your assigned role. External training resources will be provided.',
    'Role-specific training ensures personnel have the knowledge and skills required for their position.',
    10
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Continuing Education Credits',
    'Annual continuing education requirements for professional development',
    'training',
    'training',
    false,
    30,
    365,
    60,
    '{"education_provider": "text", "course_title": "text", "completion_date": "date", "credits_earned": "number", "certificate_number": "text", "relevance_statement": "textarea"}',
    '{"completion_date": {"required": true, "within_current_year": true}, "credits_earned": {"required": true, "min_value": 10}, "relevance_statement": {"required": true, "min_length": 100}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Complete minimum 10 hours of continuing education annually. Submit certificates and relevance statements.',
    'Continuing education maintains and enhances professional knowledge and skills.',
    11
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Skills Competency Assessment',
    'Periodic assessment of job-related skills and competencies',
    'assessment',
    'training',
    true,
    20,
    180,
    30,
    '{"assessment_date": "date", "skills_evaluated": "textarea", "performance_scores": "textarea", "assessor_name": "text", "improvement_plan": "textarea", "next_assessment_date": "date"}',
    '{"assessment_date": {"required": true}, "skills_evaluated": {"required": true}, "performance_scores": {"required": true}, "assessor_name": {"required": true}}',
    'pdf,xlsx,doc,docx',
    8,
    false,
    'Complete skills competency assessment every 6 months. Work with supervisor to develop improvement plans as needed.',
    'Regular competency assessments ensure skills remain current and identify development opportunities.',
    12
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Professional Development Plan',
    'Annual professional development planning and goal setting',
    'review',
    'training',
    false,
    15,
    365,
    45,
    '{"development_goals": "textarea", "training_objectives": "textarea", "timeline": "textarea", "resources_needed": "textarea", "supervisor_approval": "text", "progress_metrics": "textarea"}',
    '{"development_goals": {"required": true, "min_length": 200}, "training_objectives": {"required": true}, "supervisor_approval": {"required": true}}',
    'pdf,doc,docx',
    5,
    false,
    'Develop comprehensive professional development plan with supervisor. Include specific goals, timelines, and success metrics.',
    'Professional development planning supports career growth and organizational objectives.',
    13
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Mentorship Program Participation',
    'Active participation in mentorship program as mentor or mentee',
    'training',
    'training',
    false,
    12,
    90,
    21,
    '{"program_role": "select", "mentor_mentee_name": "text", "meeting_frequency": "select", "objectives_set": "textarea", "progress_notes": "textarea", "program_coordinator_approval": "text"}',
    '{"program_role": {"required": true}, "mentor_mentee_name": {"required": true}, "objectives_set": {"required": true, "min_length": 100}}',
    'pdf,doc,docx',
    5,
    false,
    'Participate in formal mentorship program. Submit quarterly progress reports and coordinator approval.',
    'Mentorship programs support professional growth and knowledge transfer within the organization.',
    14
);

-- Phase 3: Documentation & Record Keeping (5 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Personnel File Completeness',
    'Ensure all required documents are complete in personnel file',
    'document_review',
    'documentation',
    true,
    10,
    30,
    7,
    '{"file_review_date": "date", "missing_documents": "textarea", "documents_added": "textarea", "hr_verification": "text", "completion_status": "select"}',
    '{"file_review_date": {"required": true}, "hr_verification": {"required": true}, "completion_status": {"required": true}}',
    'pdf,doc,docx',
    5,
    false,
    'Review personnel file with HR to ensure all required documents are current and complete.',
    'Complete personnel files are required for regulatory compliance and employee record keeping.',
    15
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IP' AND tier = 'robust' LIMIT 1),
    'Training Record Maintenance',
    'Maintain accurate and current training records and certifications',
    'documentation',
    'documentation',
    true,
    15,
    ongoing,
    30,
    '{"record_system_used": "text", "last_update_date": "date", "records_verified": "checkbox", "backup_system": "text", "access_permissions": "textarea"}',
    '{"record_system_used": {"required": true}, "last_update_date": {"required": true}, "records_verified": {"required": true, "value": true}}',
    'pdf,xlsx,doc,docx',
    10,
    false,
    'Maintain organized training records including certificates, transcripts, and completion documentation.',
    'Accurate training records are essential for compliance verification and career progression.',
    16
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Performance Review Documentation',
    'Complete annual performance review documentation and goal setting',
    'review',
    'documentation',
    true,
    20,
    365,
    45,
    '{"review_period": "text", "performance_rating": "select", "goals_achieved": "textarea", "areas_for_improvement": "textarea", "new_goals": "textarea", "employee_signature": "text", "supervisor_signature": "text"}',
    '{"review_period": {"required": true}, "performance_rating": {"required": true}, "employee_signature": {"required": true}, "supervisor_signature": {"required": true}}',
    'pdf,doc,docx',
    5,
    false,
    'Complete comprehensive annual performance review with supervisor. Include goal setting for next period.',
    'Regular performance reviews support professional development and organizational alignment.',
    17
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Compliance Document Archive',
    'Maintain organized archive of all compliance-related documents',
    'documentation',
    'documentation',
    true,
    12,
    ongoing,
    60,
    '{"archive_system": "text", "document_categories": "textarea", "retention_schedule": "textarea", "access_controls": "textarea", "backup_procedures": "textarea", "last_audit_date": "date"}',
    '{"archive_system": {"required": true}, "document_categories": {"required": true}, "retention_schedule": {"required": true}, "last_audit_date": {"required": true}}',
    'pdf,doc,docx',
    8,
    false,
    'Establish and maintain organized compliance document archive with proper categorization and retention.',
    'Proper document archiving ensures compliance evidence is available for audits and reviews.',
    18
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IT' AND tier = 'basic' LIMIT 1),
    'Data Privacy Training',
    'Complete data privacy and protection training (GDPR/CCPA compliance)',
    'training',
    'documentation',
    true,
    18,
    45,
    10,
    '{"training_completion_date": "date", "privacy_laws_covered": "textarea", "assessment_score": "number", "certificate_number": "text", "policy_acknowledgment": "checkbox"}',
    '{"training_completion_date": {"required": true}, "assessment_score": {"required": true, "min_value": 80}, "policy_acknowledgment": {"required": true, "value": true}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Complete data privacy training covering GDPR, CCPA, and organizational data protection policies. Minimum 80% assessment score required.',
    'Data privacy training ensures compliance with privacy regulations and protects sensitive information.',
    19
);

-- Phase 4: Quality & Standards Requirements (4 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'IP' AND tier = 'robust' LIMIT 1),
    'Quality Standards Certification',
    'Certification in relevant quality management standards (ISO, etc.)',
    'certification',
    'quality',
    false,
    25,
    90,
    21,
    '{"standard_type": "select", "certification_body": "text", "certification_date": "date", "expiry_date": "date", "scope_of_certification": "textarea", "certificate_number": "text"}',
    '{"certification_body": {"required": true}, "certification_date": {"required": true}, "expiry_date": {"required": true, "future_date": true}, "certificate_number": {"required": true}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Obtain quality management certification from recognized standards body. External training resources available.',
    'Quality certifications demonstrate commitment to excellence and systematic quality management.',
    20
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IP' AND tier = 'robust' LIMIT 1),
    'Customer Service Excellence Training',
    'Training in customer service excellence and client relationship management',
    'training',
    'quality',
    true,
    15,
    60,
    14,
    '{"training_provider": "text", "completion_date": "date", "modules_completed": "textarea", "assessment_results": "textarea", "practical_application": "textarea", "supervisor_feedback": "text"}',
    '{"completion_date": {"required": true}, "modules_completed": {"required": true}, "supervisor_feedback": {"required": true}}',
    'pdf,doc,docx',
    5,
    true,
    'Complete customer service excellence training. Include practical application and supervisor evaluation.',
    'Excellent customer service is essential for client satisfaction and business success.',
    21
),
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Process Improvement Participation',
    'Active participation in process improvement initiatives and projects',
    'assessment',
    'quality',
    false,
    18,
    180,
    30,
    '{"project_title": "text", "role_in_project": "text", "improvement_metrics": "textarea", "implementation_status": "select", "results_achieved": "textarea", "lessons_learned": "textarea"}',
    '{"project_title": {"required": true}, "role_in_project": {"required": true}, "improvement_metrics": {"required": true}, "results_achieved": {"required": true}}',
    'pdf,xlsx,doc,docx',
    10,
    false,
    'Participate in process improvement projects. Document role, metrics, and results achieved.',
    'Process improvement participation drives organizational efficiency and innovation.',
    22
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Standards Compliance Audit',
    'Regular audit of compliance with organizational and industry standards',
    'audit',
    'quality',
    true,
    20,
    180,
    45,
    '{"audit_date": "date", "standards_reviewed": "textarea", "compliance_status": "select", "non_conformities": "textarea", "corrective_actions": "textarea", "follow_up_date": "date", "auditor_signature": "text"}',
    '{"audit_date": {"required": true}, "standards_reviewed": {"required": true}, "compliance_status": {"required": true}, "auditor_signature": {"required": true}}',
    'pdf,xlsx,doc,docx',
    15,
    false,
    'Complete comprehensive standards compliance audit. Document findings and corrective actions.',
    'Regular compliance audits ensure adherence to standards and identify improvement opportunities.',
    23
);

-- Phase 5: Leadership & Management Requirements (3 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Supervisory Skills Certification',
    'Certification in supervisory and leadership skills for management roles',
    'certification',
    'leadership',
    false,
    30,
    120,
    28,
    '{"certification_program": "text", "training_hours": "number", "completion_date": "date", "skills_assessed": "textarea", "practical_evaluation": "textarea", "certificate_number": "text"}',
    '{"certification_program": {"required": true}, "training_hours": {"required": true, "min_value": 20}, "completion_date": {"required": true}, "certificate_number": {"required": true}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Complete supervisory skills certification program. Minimum 20 hours training required with practical evaluation.',
    'Leadership certification ensures supervisors have the skills needed to effectively manage teams.',
    24
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Conflict Resolution Training',
    'Training in conflict resolution and workplace mediation techniques',
    'training',
    'leadership',
    true,
    20,
    90,
    21,
    '{"training_date": "date", "conflict_scenarios": "textarea", "resolution_techniques": "textarea", "role_play_participation": "checkbox", "assessment_score": "number", "trainer_certification": "text"}',
    '{"training_date": {"required": true}, "conflict_scenarios": {"required": true}, "role_play_participation": {"required": true, "value": true}, "assessment_score": {"required": true, "min_value": 85}}',
    'pdf,doc,docx',
    5,
    false,
    'Complete conflict resolution training with practical role-play scenarios. Minimum 85% assessment score required.',
    'Conflict resolution skills are essential for maintaining positive workplace relationships and productivity.',
    25
),
(
    (SELECT id FROM compliance_templates WHERE role = 'SA' AND tier = 'robust' LIMIT 1),
    'Strategic Planning Participation',
    'Participation in organizational strategic planning and goal setting',
    'review',
    'leadership',
    false,
    25,
    365,
    60,
    '{"planning_session_date": "date", "strategic_objectives": "textarea", "role_in_planning": "text", "action_items": "textarea", "success_metrics": "textarea", "review_schedule": "textarea"}',
    '{"planning_session_date": {"required": true}, "strategic_objectives": {"required": true}, "role_in_planning": {"required": true}, "action_items": {"required": true}}',
    'pdf,doc,docx',
    8,
    false,
    'Participate in annual strategic planning sessions. Document objectives, role, and action items.',
    'Strategic planning participation ensures alignment between individual goals and organizational objectives.',
    26
);

-- Phase 6: Specialized Role Requirements (4 requirements)
INSERT INTO compliance_requirements (
    template_id,
    name,
    description,
    requirement_type,
    category,
    is_mandatory,
    points_value,
    due_date_offset_days,
    notification_offset_days,
    form_template,
    validation_rules,
    allowed_file_types,
    max_file_size_mb,
    external_link_required,
    instructions,
    help_text,
    display_order
) VALUES
(
    (SELECT id FROM compliance_templates WHERE role = 'IC' AND tier = 'robust' LIMIT 1),
    'Instructor Certification Maintenance',
    'Maintain current instructor certifications and meet renewal requirements',
    'certification',
    'technical',
    true,
    35,
    365,
    60,
    '{"certification_type": "text", "current_expiry_date": "date", "renewal_requirements": "textarea", "continuing_education_hours": "number", "renewal_application_date": "date", "new_expiry_date": "date"}',
    '{"certification_type": {"required": true}, "current_expiry_date": {"required": true}, "continuing_education_hours": {"required": true, "min_value": 15}, "renewal_application_date": {"required": true}}',
    'pdf,jpg,jpeg,png',
    8,
    true,
    'Maintain all instructor certifications. Complete renewal requirements including continuing education before expiration.',
    'Current instructor certifications are required to maintain teaching authority and credibility.',
    27
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AP' AND tier = 'robust' LIMIT 1),
    'Provider Performance Standards',
    'Meet established performance standards for authorized providers',
    'assessment',
    'technical',
    true,
    30,
    180,
    45,
    '{"performance_period": "text", "metrics_achieved": "textarea", "client_satisfaction_score": "number", "quality_indicators": "textarea", "improvement_areas": "textarea", "action_plan": "textarea"}',
    '{"performance_period": {"required": true}, "metrics_achieved": {"required": true}, "client_satisfaction_score": {"required": true, "min_value": 4.0}, "quality_indicators": {"required": true}}',
    'pdf,xlsx,doc,docx',
    10,
    false,
    'Demonstrate achievement of provider performance standards. Minimum 4.0/5.0 client satisfaction score required.',
    'Provider performance standards ensure consistent quality and client satisfaction across all services.',
    28
),
(
    (SELECT id FROM compliance_templates WHERE role = 'AD' AND tier = 'robust' LIMIT 1),
    'Administrative Compliance Review',
    'Regular review of administrative processes and compliance requirements',
    'review',
    'compliance',
    true,
    25,
    180,
    30,
    '{"review_period": "text", "processes_reviewed": "textarea", "compliance_gaps": "textarea", "corrective_actions": "textarea", "policy_updates": "textarea", "next_review_date": "date"}',
    '{"review_period": {"required": true}, "processes_reviewed": {"required": true}, "corrective_actions": {"required": true}, "next_review_date": {"required": true}}',
    'pdf,doc,docx',
    10,
    false,
    'Conduct comprehensive review of administrative compliance. Document gaps and implement corrective actions.',
    'Regular compliance reviews ensure administrative processes meet regulatory and organizational requirements.',
    29
),
(
    (SELECT id FROM compliance_templates WHERE role = 'SA' AND tier = 'robust' LIMIT 1),
    'System Administration Certification',
    'Current certification in relevant system administration technologies',
    'certification',
    'technical',
    false,
    40,
    365,
    90,
    '{"certification_vendor": "text", "certification_name": "text", "achievement_date": "date", "expiry_date": "date", "technologies_covered": "textarea", "practical_experience": "textarea"}',
    '{"certification_vendor": {"required": true}, "certification_name": {"required": true}, "achievement_date": {"required": true}, "expiry_date": {"required": true, "future_date": true}}',
    'pdf,jpg,jpeg,png',
    5,
    true,
    'Maintain current system administration certifications relevant to your role. External training resources available.',
    'System administration certifications ensure technical competency for managing critical systems.',
    30
);

-- Create performance indexes for efficient queries
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_template_category ON compliance_requirements(template_id, category);
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_mandatory ON compliance_requirements(is_mandatory) WHERE is_mandatory = true;
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_points ON compliance_requirements(points_value DESC);
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_due_date ON compliance_requirements(due_date_offset_days);
CREATE INDEX IF NOT EXISTS idx_compliance_requirements_display_order ON compliance_requirements(display_order);

-- Update table statistics for query optimization
ANALYZE compliance_requirements;

-- Insert audit log entry
INSERT INTO public.audit_logs (
    action,
    entity_type,
    details
) VALUES (
    'migration_applied',
    'compliance_requirements',
    jsonb_build_object(
        'migration', 'Migration 14: Insert comprehensive default compliance requirements',
        'description', 'Added 30 comprehensive compliance requirements across 6 major categories',
        'categories', jsonb_build_array(
            'Core Safety & Certification (8 requirements)',
            'Training & Education (6 requirements)',
            'Documentation & Record Keeping (5 requirements)',
            'Quality & Standards (4 requirements)',
            'Leadership & Management (3 requirements)',
            'Specialized Role Requirements (4 requirements)'
        ),
        'total_requirements_added', 30,
        'role_coverage', jsonb_build_array('SA', 'AD', 'AP', 'IT', 'IP', 'IC'),
        'tier_coverage', jsonb_build_array('basic', 'robust'),
        'timestamp', NOW()
    )
);

-- Completion message
SELECT 'Migration 14: Insert comprehensive default compliance requirements - COMPLETED SUCCESSFULLY' as result,
       'Added 30 enterprise-grade compliance requirements covering all major areas and roles' as description,
       '6 major categories: Safety, Training, Documentation, Quality, Leadership, and Specialized Requirements' as coverage;
