// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrrqnwzfaqdlzmlmhmdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZycnFud3pmYXFkbHptbG1obWRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1MjgzNjAsImV4cCI6MjA1NjEwNDM2MH0.tPB5tSjfvrYBeKAjMYJT3u4tk2weWXrw9r4znlxnHBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);